services:
  postgres:
    image: postgres:17
    container_name: pg_container
    environment:
      POSTGRES_USER: gamote
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: shortener
    ports:
      - "5433:5432"
    volumes:
      - docker_pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network

  shortenerapi:
      build: .
      container_name: shortenerapi
      ports:
        - "7000:7000"
      environment:
        ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=shortener;Username=gamote;Password=testPassword"
      depends_on:
        - postgres
      networks:
        - app-network

volumes:
  docker_pg_data:

networks:
  public-network:
    driver: bridge
  app-network:
    driver: bridge
